project:
  type: website
  output-dir: docs

website:
  title: "Thoughts on Things"
  site-url: https://mftokic.github.io
  open-graph: true
  twitter-card: true
  favicon: logo.png
  description: "A collection of thoughts on things from the mind of Mike Tokic"
  navbar:
    right:
      - text: "Start Here"
        file: start_here.qmd
      - about.qmd
      - text: "Software"
        file: software.qmd
      - icon: github
        href: https://github.com/mftokic
      - icon: rss
        href: index.xml
format:
  html:
    theme: cyborg
    css: styles.css



