---
title: "Books That Changed My Life"
---

### Better Life 

- [The Alamanack of Naval Ravikant](https://a.co/d/crZWpii)
    - [Review](https://mftokic.github.io/posts/2023-12-30-naval-book/)
- [Tools of Titans](https://a.co/d/dQsTYXz)
- [The Essential Wooden](https://a.co/d/4Xk3z9z) 
- [The Anthology of Balaji](https://a.co/d/7QqpPoP) 
- [Same as Ever](https://a.co/d/h4Gnzkh) 
- [The Psychology of Money](https://a.co/d/a0wS9q3) 
- [The 4-Hour Workweek](https://a.co/d/807kjQ6) 
- [Tribe of Mentors](https://a.co/d/17BeUMU) 
- [Die With Zero](https://a.co/d/6rp1z1f)
- [Scarcity Brain](https://a.co/d/3Zvtq0v) 
- [The Comfort Crisis](https://a.co/d/0DWDHof) 
- [Clear Thinking](https://a.co/d/iskLDlo) 
- [Be Useful](https://a.co/d/fGAAVFD) 
- [How to Win Friends and Influence People](https://a.co/d/0BuoA8j) 
- [The Art of Learning](https://a.co/d/0sTDPsQ) 
- [Vagabonding](https://a.co/d/9fidOhp) 
- [Tuesday's With Morrie](https://a.co/d/fW1iUit)
- [Range](https://a.co/d/2K1TX8Q) 
- [Mastery](https://a.co/d/73jYaat) 
- [Four Thousand Weeks](https://a.co/d/9mAQGmd) 
- [The Great Mental Models](https://a.co/d/feiSnef) 
- [Extreme Ownership](https://a.co/d/hJCx3ez) 
- [The Dichotomy of Leadership](https://a.co/d/imGJCcX) 
- [The Coddling of the American Mind](https://a.co/d/fIAYoBg) 
- [The Anxious Generation](https://a.co/d/4bjA1o1)
- [Excellent Advice for Living](https://a.co/d/2d7dRml) 
- [Stillness is the Key](https://a.co/d/gHVYK68) 
- [The Obstacle is the Way](https://a.co/d/ftiqhOR) 
- [Ego is the Enemy](https://a.co/d/6WGZdCX) 
- [The Algebra of Happiness](https://a.co/d/ePmlrWu)
- [Essentialism](https://a.co/d/9eFwdlI) 
- [Principles](https://a.co/d/0PWw75o)
- [Walkable City](https://a.co/d/5Ry8Tex)
- [Discipline Equals Freedom](https://a.co/d/86hV0AC)
- [Atomic Habits](https://a.co/d/8g41hIh)
- [The 7 Habits of Highly Effective People](https://a.co/d/7hW4cRC) 
- [A Mind for Numbers](https://a.co/d/981NWqD) 
- [Drive](https://a.co/d/4MRjLVG) 
- [The Algebra of Wealth](https://a.co/d/7eMvnCu) 
- [Storyworthy](https://a.co/d/4AP0Ba2)
- [Make it Stick](https://a.co/d/8Yl8arM)
- [Save the Cat](https://a.co/d/9822oZz)

### Business and Technology

- [Zero to One](https://a.co/d/cHMChgC) 
- [Loonshots](https://a.co/d/8okiYup)
- [What's The Future](https://a.co/d/2xPzmz8) 
- [How Google Works](https://a.co/d/i7DP37D) 
- [Trillion Dollar Coach](https://a.co/d/3PLoJzi) 
- [How Innovation Works](https://a.co/d/bpiMlYT)  
- [Read This Before Our Next Meeting](https://a.co/d/f1GQXHz) 
- [Build](https://a.co/d/3qN8L24) 
- [The Inevitable](https://a.co/d/d33xeb6)
- [The New One Minute Manager](https://a.co/d/dEP66vU)
- [Creativity Inc](https://a.co/d/eaFWuT6) 
- [Good to Great](https://a.co/d/9zpUo66) 
- [Rework](https://a.co/d/bSZc6Ny)

### History

- [Guns, Germs, and Steel](https://a.co/d/eOV6YM1) 
- [Coders](https://a.co/d/i3uABiu) 
- [Kitchen Confidential](https://a.co/d/8rUGuU1) 
- [Hatching Twitter](https://a.co/d/20Q13XU)
- Elon Musk
    - [One](https://a.co/d/a9N0gxu) 
    - [Two](https://a.co/d/gvbNQk1)
- [Let My People Go Surfing](https://a.co/d/evhnRz7)
- [Don't Tell Me I Can't](https://a.co/d/17qTrlm) 
- [The Promise of a Pencil](https://a.co/d/3HqpMHL) 
- [Total Recall](https://a.co/d/epggQYS) 
- [Empire of the Summer Moon](https://a.co/d/dOqs32n) 
- [Surely You're Joking Mr. Feynman!](https://a.co/d/5AwoesS)
- [Natural Born Heroes](https://a.co/d/f0RUD2q) 
- [Eat & Run](https://a.co/d/6J7b8Zd)
- [The New Jim Crow](https://a.co/d/8EutVs7)
- [Genghis Khan and the Making of the Modern World](https://a.co/d/8RjV2ye)
- [Permanent Record](https://a.co/d/ejfvN1H)
- [In the Weeds](https://a.co/d/aarVD7p)
- [Fear and Loathing in Las Vegas](https://a.co/d/2cHi515) 
- [Sapiens](https://a.co/d/2mOShOL) 
- [Homo Deus](https://a.co/d/1YayXCD) 
- [Steve Jobs](https://a.co/d/cnQ1WZU)
- [Greenlights](https://a.co/d/h8jSR59) 
- [Not Fade Away](https://a.co/d/bvJWrHI)
- [Into the Wild](https://a.co/d/5EHxFLk)

### Health

- [Born to Run](https://a.co/d/c6dUa5P) 
- [Breath](https://a.co/d/aLiLd4n) 
- [The Four Hour Body](https://a.co/d/7ixne61)
- [Magic Pill](https://a.co/d/9kWYp66)

### Fiction 

- [Harry Potter](https://a.co/d/dp99O8G)
- [A Game of Thrones](https://a.co/d/imQJLWG)
- [Red Rising](https://a.co/d/dpoc8nn)
- [The Chronicles of Narnia](https://a.co/d/6gQl8do)
- [Jack Reacher](https://a.co/d/6bA6rXH)
- [The Alchemist](https://a.co/d/iM0QEZm)
- [Ready Player One](https://a.co/d/iliEDCu)  
- [Shantaram](https://a.co/d/h4XGW1K) 
- [The Graveyard Book](https://a.co/d/3RzYHIR) 