---
title: "How I Try to Stay Healthy"
---

**Last Updated: March 2026**

### Diet

- Whole foods, no processed foods. Limit seed oils.
- 0.7-1 gram of protein per ideal body weight, so around 150 grams per day. 
- Stop eating 4 hours before bed.  

### Supplements

- Essentials for Everyone
    - [Creatine Monohydrate](https://a.co/d/aUD3imc) by Momentous
    - [Omega 3 Fish Oil](https://a.co/d/fTlqdxr) by Momentous
    - [Vitamin D3](https://a.co/d/0hfwmoHR) by Designs for Health
    - [Methylated Multivitamin](https://a.co/d/0hFwLvDd) by Pure Encapsulations
    - [Magnesium Breakthrough](https://a.co/d/7k1WBv4) by BIOptimizers
    - [Essential Amino Acids](https://a.co/d/647Du5X) by BodyHealth
    - [Sea Salt](https://a.co/d/bEIgQMg) by Baja Gold
    - [Whey Protein](https://a.co/d/02FsEobQ) by Transparent Labs
    - [Minerals](https://a.co/d/08NhvRNn) by SuppGrade Labs
    - [Collagen](https://a.co/d/0guEFl0D) by Blueprint
    - [L-Theanine](https://a.co/d/05XsMnMs) by Bluebonnet
    - Various Fiber Supplements
        - [Prebiotic Fiber](https://a.co/d/g90viZU) by Supergut
        - [Fiber+](https://www.livemomentous.com/products/fiber-plus) by Momentous
- Specific to My Lab Testing
    - [TMG](https://a.co/d/03vVdRte) by Double Wood 
    - [5-MTHF](https://a.co/d/0iYgmRyL) by Thorne
    - [NAD+](https://a.co/d/03w0dkSG) by Qualia
    - [Gut](https://www.viome.com/products/precision-probiotics-prebiotics) and [Oral](https://www.viome.com/products/vrx-oral-lozenges) Probiotics by Viome
    - [Colostrum](https://shop.heartandsoil.co/products/free-form-grass-fed-colostrum) by Heart and Soil 
    - [Whole Package](https://shop.heartandsoil.co/products/whole-package) by Heart and Soil
    - [Thyroid+](https://shop.heartandsoil.co/products/grass-fed-thyroid) By Heart and Soil
    - [GLP-1 Postbiotic](https://a.co/d/04zG2zqV) by resM
    - [Ubiquinol](https://a.co/d/0hJj1now) by Jarrow Formulas

### Water Filtration

- [Countertop Reverse Osmosis Filter](https://aquatruwater.com/) by AquaTru
- [Shower Head Filter](https://jolieskinco.com/) by Jolie

### Air Filtration

- [Jaspr Air Scrubber](https://jaspr.co/)

### Health Tracking

- Wearables
    - [Whoop](https://www.whoop.com/us/en/)
    - [Eight Sleep](https://www.eightsleep.com/)
    - [Blood Glucose Monitor](https://a.co/d/0eXEXiiQ) by Dexcom one month a quarter
    - [Brain Neurofeedback](https://info.40yearsofzen.com/#features) by Satoria
- Lab Testing 
    - [Blood Biomarkers](https://www.functionhealth.com/) by Function
    - [Microbiome](https://www.viome.com/products/full-body-intelligence) by Viome 
    - [Mitochondria](https://www.mito.me/) by Mitome
    - [Toxins](https://vibrant-wellness.com/tests/toxin-zoomer) by Vibrant Wellness
    - [Microplastics](https://blueprint.bryanjohnson.com/products/microplastics-test) by Blueprint
    - [Speed of Aging](https://www.trudiagnostic.com) by TruDiagnostics
    - [NAD+](https://www.jinfiniti.com/) by Jinfinity
    - [Full Genome Sequencing](https://selfdecode.com/?nab=1) by SelfDecode

### Exercise

- 10k steps every day
- Zone 2 cardio 3x per week
    - Peloton cycle on Tuesday/Thursday
        - 30-60 min
    - Rucking on Sunday with 20-45 pound weight for 1-3 miles
- HIIT 1x per week 
    - Norwegian 4x4 every Saturday using Peloton cycle
- Strength training 3x per week
    - 4 week mesocycle
        - First 3 weeks of progressive overload
        - Last week of deload with half the weight, half the reps, and half the sets
        - Push/Legs/Pull Split
    - Push on Monday 
        - Chest Fly with Dumbbells 
        - Overhead Press with Dumbbells 
        - Tricep Extension with Dumbbells
        - Reverse Crunch 
    - Legs on Tuesday
        - Bulgarian Split Squat Dumbbells 
        - Romanian Deadlift Dumbbells 
        - Calf Extensions 
        - Tibialis Raises 
        - Russian Twist with Dumbbells
    - Pull on Friday 
        - Pullups 
        - Bicep Curls with Dumbbells 
        - Lawn Mower Rows with Dumbbells
        - Bicycle Kicks
- All training tracked via [Whoop](https://www.whoop.com/us/en/)

### Morning Routine

- Wake up at 4:40am
- Oral care 
    - [Toothpaste](https://a.co/d/7hZ3JRn) 
    - [Tongue Scraper](https://a.co/d/1pNk2Nu)
- Cold Plunge at 50 degrees for 2 minutes 
- Take morning supplements 
    - Creatine, Perfect Aminos, Fiber, Probiotic, Sea Salt in shaker bottle
    - Postbiotic, Whole Package, Thyroid+
- Get light in my eyes using [10k lux lamp](https://a.co/d/0a3DCEcC) for 10 minutes
    - [Wim Hoff breathwork](https://www.youtube.com/watch?v=tybOi4hjZFQ) while using light lamp
- 20 min [red light therapy](https://boncharge.com/products/full-body-red-light-therapy-bundle)
- Perform exercise of the day 
- Consume whey protein and collagen
- Shower and get ready for work 
    - [Bar Soap](https://a.co/d/0eX6G8VP) by Dr. Bronner
    - [Shampoo+Conditioner](https://a.co/d/00nCxg1B) by Pura D'Or
    - [Facial Cleanser](https://a.co/d/0j78Y0Rf) by Blueprint
    - [Moisturizer](https://a.co/d/0ehEM2e7) by OneSkin
    - [Sunscreen](https://a.co/d/0eeWJmeh) by OneSkin
    - [Hair Serum](https://a.co/d/0bllzF6i) by OneSkin
    - [Deodorant](https://a.co/d/0c2GyZcq) by Native
- Journal using an [app called Day One](https://dayoneapp.com/), answering the following prompts
    - I am grateful for...
    - Morning exercise 
    - What's the most important question for today?
    - What will you have a sense of urgency about today?
    - What will you have a bias for action about today? 
    - What would make today great? 
    - Daily affirmation
- Write for 30-60 minutes about anything that interests me 
- Eat first meal around 7am and take rest of supplements (excluding supplements taken during evening routine)
- Kick ass the rest of the day

### Evening Routine

- 6:00pm put on [blue light blocking glasses](https://truedark.com/), 30 min [sauna](https://boncharge.com/products/infrared-sauna-blanket), then shower
- 6:45pm oral, face, hair care
    - same as morning, add [floss](https://a.co/d/0gRCtIC8)
- 7:00pm do the following exercises
    - 10 min breathwork 
    - 15 min [neurofeedback session](https://info.40yearsofzen.com/#features)
- 7:30pm dim all lights, stop looking at screens, and take supplements
    - 5-MTHF, Magnesium Breakthrough, L-Theanine
- Fall asleep by 9:00pm