---
title: "Hire Me"
---

I like my current job. I'm good at my current job. The sad fact is that all jobs eventually end, and that's ok. While I'm not actively looking for a new job, I created this as a way for new opportunities to come and find me. 

If you'd like to hire me for a job, here's what I'm interested in. 

### Commando, Soldier, Police

When it comes to job types, I'd rather [be a commando/soldier than a policeman](https://eugeneyan.com/writing/commando-soldier-police-and-your-career/). 

### Building or Selling

> “If you can build and sell, you will be unstoppable.”
>
> — Bill Gates

I'd like to work on building products that make money, help sell them, or both. In this new AI age, most jobs will come down to building the product/service or selling it. Anything that's secondary/tertiary to that will be a line item on the P&L the CEO will look to minimize using AI. I'd like to work in profit centers, not cost centers. 

### Where AI Matters Most

AI will totally redefine health and education in ways we can't imagine. These are the biggest areas of impact for AI. No one is going to feel bad when hot shot doctors get displaced by low cost AI tools, but we will feel bad if your local elementary school teacher gets laid off because of AI tutors. Solving problems the right way with AI in the health and education space is the most important problem in the world right now. Everyone can benefit from being healthier and more intelligent. As machines continue to become more advanced, so should humans. 

Here's a prioritized list of industries I'm the most interested in working with AI. 

1. Health 
    - Wearables
    - Lab Testing
    - Supplements
2. Education
    - AI Tutors 
    - New School Paradigms
    - Giving People AI+Data Superpowers
3. Factories
    - Robotics
    - Building Things That Build The Thing (e.g. software factories like coding agents)
4. Business Analytics
    - AI Co-Workers (agents)
    - Forecasting

### Final Thoughts

If you're hiring, and the role fits into what I described above (even barely) then I'd like to talk to you. You can [find me on LinkedIn](https://www.linkedin.com/in/michaeltokic/), please message me there and I will get in touch. 