---
title: "Pro Bono Work for Stretch Projects"
description: "Getting experience before you're qualified to do the work"
author: "Mike Tokic"
date: "2021-08-24"
categories: [code, learning]
---

Want to learn a new skill for your career? There are tons of places to learn the actual skill, from in person classes to free YouTube videos. What is sometimes the hard part is the application of the skill that is often required when trying to transition jobs or career paths. You know, the whole "experience" word employers throw out in job postings. Even entry level jobs ask for so many years of experience. This leads to a chicken or the egg problem. You need experience to get a job, but you need to get a job to gain experience. 

Technical roles like data science and analytics suffer from this problem in a big way, where you normally see job postings asking for PHD's or having 10 years of experience. The term data science has barely been around for 10 years, this is crazy. 

### The Third Door

Alex Banayan in his book [The Third Door](https://thirddoorbook.com/) talks about different paths one can take to get what they want in life. Below is a good summary of the third door concept from the book. 

> Life, business, success… it’s just like a nightclub.
There are always three ways in.
There’s the First Door: the main entrance, where 99 percent of people wait in line, hoping to get in.
The Second Door: the VIP entrance, where the billionaires and celebrities slip through.
But what no one tells you is that there is always, always… the Third Door. It’s the entrance where you have to jump out of line, run down the alley, bang on the door a hundred times, crack open the window, sneak through the kitchen—there’s always a way.

The first door in getting experience may be something like getting a traditional degree from a college and having a few years of experience at an entry level position. Most follow this path, which leads it to becoming the most crowded and therefor competitive path for getting good experience. 

The second door could be experience in an adjacent field. A more general software engineer could have an easier time leveraging their experience to transition into a data science role than someone who worked as an archeologist for many years. This is more non-traditional but still can have a good shot at working out well. 

The third door is the most nuanced of them all, with many paths to gaining experience and ultimately a job in the new career of your choice (like data science). One path I think works well is gaining experience through pro bono project work. 

### Non-Profits Need All the Help They Can Get

What kind of organizations are always strapped for cash, desperately short on staff, and would take in just about any person claiming to have technical skills? That's right, you guessed it, charities! 

Non-profit organizations are always looking for help, and it doesn't matter if it's only for a few hours a week! This presents an amazing opportunity for someone who just learned some new skills to go out and immediately apply them within a real world setting. Volunteering for a non-profit outside of your existing job is an excellent way to build up experience that can then be leveraged when transitioning careers. It's truly the best of both worlds. You gain valuable experience, and the non-profit gets the help they desperately need. This comes with the added bonus of helping to make the world a better place 😊. 

I'll use myself as an example. When I was trying to transition from a financial analyst to a data scientist, I tried looking for volunteer opportunities to sharpen my data skills. I eventually found one with helping the [Microsoft Airband](https://www.microsoft.com/en-us/corporate-responsibility/airband) team analyze hundreds of government broadband policy documents for insight around digital inclusiveness online. It wasn't hard core data scientist work with deep learning, but it helped me gain skills in natural language processing (NLP) and data visualization. Those are two skills that are great to have for any data scientist job. 

At the time I had zero experience but was eager to help them, and they in turn provided the opportunity for me to earn my "data stripes" and ultimately get over a large hurdle for anyone learning a new skill. The imposter syndrome feeling. I continued to learn more about NLP and what makes for compelling visualizations as I went along. Getting that experience taught me a lot about how to be the data person within a broader team and how to create insights for others to easily leverage. Some of my initial work ended up on a [website](http://broadbandpolicy.org/) about broadband policies, and now I'm working on an even better site that will analyze more types of government policies! This will allow me to gain more experience on a new skill I'm learning, web development. 

## Final Thoughts

When learning something new, the best way to master it is by applying it in the real world on something that matters. That could be something within your current job, but oftentimes what you are learning are skills you want to grow into a different job or career. In order to gain experience in those skills before making that job switch, consider volunteering for a non-profit. They would be thrilled to have you. 
